name: engine
description: This package provides engine core, such as helpers, services, dependencies and reusable components.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: 11.5.0
  firebase_core: 3.14.0
  firebase_crashlytics: 4.3.7
  firebase_messaging: 15.2.7
  firebase_remote_config: 5.4.5
  get: 4.7.2
  get_storage: 2.1.1
  lucid_validation: 1.3.1
  intl: 0.20.2
  package_info_plus: 8.3.0
  url_launcher: 6.3.1
  internet_connection_checker_plus: 2.7.2

  design_system:
    git:
      url: https://github.com/moreirawebmaster/DesignSystem.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
